name: handbook
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - jupyterlab
  - jupyterlab-git
  - pooch
  - pandas
  - xarray
  - openpyxl
  - tabulate
  - markdown
  - panel=0.14.1
  - cdflib