name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: pip install markdown pandas panel tabulate
      - name: make html
        run: |
          cd json
          make html
          cd ..
      - name: Gather resources to deploy
        run: |
          mkdir to_deploy
          mkdir to_deploy/old
          cp -r ./json/html/* to_deploy/
          cp -r ./old/output/* to_deploy/old
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./to_deploy
